/**
 * HeroForm — Single-step "Start Your Analysis" form.
 * Collects business name, location, optional description. Queries are
 * generated by the backend so the report can explain why each query was chosen.
 */

import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { createBusiness, triggerScan } from '../lib/api'

export function HeroForm() {
  const navigate = useNavigate()
  const [bizName, setBizName]     = useState('')
  const [location, setLocation]   = useState('')
  const [description, setDescription] = useState('')
  const [isSubmitting, setSubmitting]  = useState(false)
  const [error, setError]              = useState('')

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!bizName.trim()) { setError('Please enter your business name.'); return }
    if (!location.trim()) { setError('Please enter your business location.'); return }

    setSubmitting(true)
    setError('')

    try {
      const { data: { session } } = await supabase.auth.getSession()
      if (!session) {
        const params = new URLSearchParams({
          name: bizName.trim(),
          location: location.trim(),
          description: description.trim(),
        }).toString()
        navigate(`/auth?${params}`)
        return
      }

      const { business_id } = await createBusiness({
        name: bizName.trim(),
        location: location.trim(),
        description: description.trim() || undefined,
        generate_queries: true,
        query_count: 5,
      })
      const { scan_id } = await triggerScan(business_id)
      navigate(`/dashboard?scanId=${scan_id}`)
    } catch (err: any) {
      setError(err.message ?? 'Something went wrong. Please try again.')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <form className="analyze-form" id="hero-form" onSubmit={handleSubmit}>
      <h2 className="analyze-form-title">Start Your Analysis</h2>

      <div className="form-group">
        <label htmlFor="biz-name">Business Name</label>
        <input
          type="text"
          id="biz-name"
          name="business_name"
          placeholder="Business Name"
          required
          autoComplete="organization"
          value={bizName}
          onChange={e => setBizName(e.target.value)}
        />
      </div>

      <div className="form-group">
        <label htmlFor="biz-location">Location (City, Country)</label>
        <input
          type="text"
          id="biz-location"
          name="location"
          placeholder="Location (City, Country)"
          required
          autoComplete="address-level2"
          value={location}
          onChange={e => setLocation(e.target.value)}
        />
      </div>

      <div className="form-group">
        <label htmlFor="biz-desc">Business Description (optional)</label>
        <textarea
          id="biz-desc"
          name="description"
          placeholder="Optional..."
          rows={3}
          value={description}
          onChange={e => setDescription(e.target.value)}
        />
      </div>

      {error && <p className="analyze-error">{error}</p>}

      <button type="submit" className="btn-primary analyze-btn" disabled={isSubmitting}>
        {isSubmitting ? (
          <>
            <div className="spinner" />
            Analyzing...
          </>
        ) : (
          'Analyze My Brand'
        )}
      </button>
    </form>
  )
}
