/**
 * HeroForm — Single-step "Start Your Analysis" form.
 * Collects business name, location, and short description. Queries are
 * generated by the backend so the report can explain why each query was chosen.
 */

import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../contexts/auth-context'
import { createBusiness } from '../lib/api'

export function HeroForm() {
  const navigate = useNavigate()
  const { session } = useAuth()
  const [bizName, setBizName]     = useState('')
  const [location, setLocation]   = useState('')
  const [description, setDescription] = useState('')
  const [isSubmitting, setSubmitting]  = useState(false)
  const [error, setError]              = useState('')

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!bizName.trim()) { setError('Please enter your business name.'); return }
    if (!location.trim()) { setError('Please enter your business location.'); return }
    if (!location.includes(',')) { setError('Please enter a precise location like "Brookings, SD".'); return }
    if (description.trim().length < 10) { setError('Please add a short description of what your business does.'); return }

    setSubmitting(true)
    setError('')

    try {
      if (!session) {
        const params = new URLSearchParams({
          name: bizName.trim(),
          location: location.trim(),
          description: description.trim(),
        }).toString()
        navigate(`/auth?${params}`)
        return
      }

      const { business_id, default_set_id, tier, queries } = await createBusiness({
        name: bizName.trim(),
        location: location.trim(),
        description: description.trim(),
        generate_queries: true,
        query_count: 5,
      })
      navigate(`/preview/${business_id}`, {
        state: { queries, tier, defaultSetId: default_set_id },
      })
    } catch (err: any) {
      setError(err.message ?? 'Something went wrong. Please try again.')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <form className="analyze-form" id="hero-form" onSubmit={handleSubmit}>
      <h2 className="analyze-form-title">Start Your Analysis</h2>

      <div className="form-group">
        <label htmlFor="biz-name">Business Name</label>
        <input
          type="text"
          id="biz-name"
          name="business_name"
          placeholder="Business Name"
          required
          autoComplete="organization"
          value={bizName}
          onChange={e => setBizName(e.target.value)}
        />
      </div>

      <div className="form-group">
        <label htmlFor="biz-location">Location (City, State)</label>
        <input
          type="text"
          id="biz-location"
          name="location"
          placeholder="Brookings, SD"
          required
          autoComplete="address-level2"
          value={location}
          onChange={e => setLocation(e.target.value)}
        />
      </div>

      <div className="form-group">
        <label htmlFor="biz-desc">
          What does your business do?
          <span className="form-label-hint">Be specific — better description = more accurate scan</span>
        </label>
        <textarea
          id="biz-desc"
          name="description"
          placeholder="e.g. residential roofing company specializing in storm damage repair and insurance claims"
          rows={3}
          required
          minLength={10}
          value={description}
          onChange={e => setDescription(e.target.value)}
        />
        <p className="form-field-hint">
          The queries AI uses to find your business are generated from this description. The more specific you are, the more relevant your results.
        </p>
      </div>

      {error && <p className="analyze-error">{error}</p>}

      <button type="submit" className="btn-primary analyze-btn" disabled={isSubmitting}>
        {isSubmitting ? (
          <>
            <div className="spinner" />
            Generating prompts…
          </>
        ) : (
          'Generate My Prompts'
        )}
      </button>
    </form>
  )
}
