-- Store the business context used to generate free-scan queries.
alter table public.businesses
  add column if not exists location text;

-- Track whether a query was generated by Visaion or supplied by the user.
alter table public.queries
  add column if not exists source text default 'custom'
    check (source in ('generated', 'custom')),
  add column if not exists intent text,
  add column if not exists generation_reason text;

-- Atomically create a scan for a user. Free users are allowed one in-flight or
-- completed scan total; failed scans do not consume the free scan.
create or replace function public.create_scan_if_allowed(
  p_business_id uuid,
  p_user_id uuid
)
returns table(scan_id uuid, allowed boolean, reason text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_subscription_status text;
  v_business_exists boolean;
  v_blocking_scan_count integer;
  v_scan_id uuid;
begin
  perform pg_advisory_xact_lock(hashtext(p_user_id::text));

  select exists(
    select 1
    from public.businesses
    where id = p_business_id
      and user_id = p_user_id
  )
  into v_business_exists;

  if not v_business_exists then
    return query select null::uuid, false, 'business_not_found'::text;
    return;
  end if;

  select subscription_status
  into v_subscription_status
  from public.profiles
  where id = p_user_id;

  if coalesce(v_subscription_status, 'free') <> 'active' then
    select count(*)
    into v_blocking_scan_count
    from public.scans s
    join public.businesses b on b.id = s.business_id
    where b.user_id = p_user_id
      and s.status in ('pending', 'running', 'completed');

    if v_blocking_scan_count >= 1 then
      return query select null::uuid, false, 'subscription_required'::text;
      return;
    end if;
  end if;

  insert into public.scans (business_id, status, triggered_by)
  values (p_business_id, 'running', 'manual')
  returning id into v_scan_id;

  return query select v_scan_id, true, null::text;
end;
$$;
